### ISSUE TITLE
Only last file of an array exports

### ISSUE THREAD

**Issue by Grawl** [rrott/grunt_coffee_chain#4]
my grunt task looks like this:

```js
expand:true,
cwd:'src/scripts/',
dest:'dest/scripts/',
src:'*.coffee',
ext:'.js'
```

and `src/scripts/` looks like this:

```
scripts/
  test.coffee
  main.coffee
```

And in my `dest/scripts/` folder I see only last item in alphanumeric sorting, `test.js`.

I checked twice with a bunch of files different named like `a`, `z`, `0`, `4`. Only one last item.

**Comment by rrott** [comment]
Sorry for the delay with answering. I've missed this message accedentaly. 
It was designed to work this way. This task check the file described in "dest" param and check all required there dependencies in that file. Like:

```
  dist:
    src:  "main.coffee"
    dest: "main.js"

  test:
    src:  "spec/test.coffee"
    dest: ".tmp/spec/test.js"
```
Where "main.coffee" look like
```
#= require config
#= require view
#= require_tree models

$ ->
```

Anyway I consider this as a bug cause you should have been notified that the dist param was incorrect, instead of using the last file in the folder.
